name: "My Action"
description: "Test my Action"

inputs:
  myInput:
    description: "My Input"
    required: true
    default: "Hello World"
  nombre:
    description: "EL nombre"
    required: true
    default: "Pollo"

runs:
  using: "composite"
  steps:
    - name: Hola Mundo
      shell: bash
      run: echo "${{ inputs.myInput }}"
    
    - name: touch file
      shell: bash
      run: touch file.txt

    - name: Set text
      shell: bash
      run: echo "Hello ${{ inputs.nombre }}" >> file.txt

    - name: Read file
      shell: bash
      run: cat file.txt
