name: Test


on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: LS
      run: |
        chmod +x script.sh
        ./script.sh


    # - name: Checkout
    #   uses: actions/checkout@v4.1.7

    # - name: Install dependencies
    #   run: npm install

    # - name: Build
    #   run: npm run build

    # - name: Test
    #   run: npm test